---
author: "Roysvork"
email: "roysvork@gmail.com"
title: "Superscribe"
subtitle: "Make Routing a First Class Citizen in your Web Application"
url: "https://github.com/roysvork/superscribe"
description: ""
short_description: "Super flexible, ultra expressive graph based routing for Asp.Net"

theme:          plain
permalink:      /:title
markdown: rdiscount